name: Crystal CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: nix build .#crystal2nix
      - name: Run offline tests
        run: nix build .#checks.specs-offline --print-build-logs
      - name: Run online prefetch tests
        run: nix develop -c make test-online
